#!/usr/bin/env node
/**
 * check-lexicon — the floor is complete, and no lexicon spells a key nobody reads.
 *
 *   node scripts/check-lexicon.mjs
 *
 * Three findings, two of them fatal:
 *
 *   FAIL  a key the client reads (`t('key', …)` in public/js)
 *         is missing from `ronin_catalogs/lexicons/professional_en.md` — the floor is
 *         complete BY DEFINITION, so this is the build's mistake, in the same commit as
 *         the view that added the key.
 *   FAIL  a shipped lexicon other than the floor carries a bare key the floor does not
 *         — a typo, since every word has to fall through to something. Prefixed keys
 *         (`kind.*`, `role.*`, `team_role.*`, `behaviour.*`) are exempt: they name
 *         catalog tokens, and the definition's own label is their floor.
 *   note  keys the floor carries that no view reads yet — allowed, because the surfaces
 *         that will read them (the campaign board) are not built; reported so the list
 *         cannot rot in silence.
 *   note  modules that import `t` AND declare a local named `t` (a parameter, a `const`,
 *         a `let`, a loop variable) — legal, but every such scope is one where a bare
 *         `t` is the local and not the word; listed so a reviewer reads those scopes.
 *         (hotwords.js, 2026-08-27: a rename left two reads on the local behind.)
 *
 *   FAIL  the `glossary.*` room and KOTOBA_GLOSSARY.md disagree — a marked cell whose word
 *         is not the floor's word, a floor glossary key no cell carries, or a table row
 *         with a bold UI word and no marker. The boot shelf renders the glossary from this
 *         room at session birth; this is what keeps the agent's word the owner's word.
 *   FAIL  a module calls `t()` and does not import it from `./lexicon.js` — in code, not
 *         in a comment. Static checks cannot see an undefined reference; the grid can.
 *   FAIL  `docs/kokugo-table.md` is behind the catalog — it is generated by
 *         `scripts/kokugo-table.mjs` (one table: every key, the floor's word, every
 *         lexicon's word beside it); regenerate and commit it with the words.
 *
 * `public/index.html` is read too: an element's `data-t`, `data-t-title` and `data-t-aria`
 * name keys the boot pass (`public/js/pagewords.js`) fills, and they must be in the floor
 * like any `t()` call.
 *
 * The sweep landed 2026-08-27 (KOKUGO): every view reads its strings through `t()`. A
 * literal that is not is a finding for a reviewer, not for this script — this checks what
 * IS read, nothing about what is not.
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const JS = path.join(ROOT, 'public', 'js');
const LEX = path.join(ROOT, 'ronin_catalogs', 'lexicons');
const FLOOR = 'professional_en';
const FIELDS = new Set(['label', 'blurb', 'base', 'order', 'hidden']);
const PREFIXED = /^(kind|role|team_role|behaviour)\./;

const keysOf = (file) => {
  const out = new Set();
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    const m = /^-\s*\*\*([\w.-]+):\*\*/.exec(line.trim());
    if (m && !FIELDS.has(m[1])) out.add(m[1]);
  }
  return out;
};

const lexicons = fs.readdirSync(LEX).filter((f) => f.endsWith('.md') && f !== 'README.md');
const floor = keysOf(path.join(LEX, `${FLOOR}.md`));

// What the client reads: t('key' …) with a literal first argument.
const read = new Set();
const shadowers = [];
const fails = [];
for (const f of fs.readdirSync(JS).filter((f) => f.endsWith('.js'))) {
  const src = fs.readFileSync(path.join(JS, f), 'utf8');
  for (const m of src.matchAll(/\bt\(\s*'([\w.-]+)'/g)) read.add(m[1]);
  // A module that calls t() must import it — in code, not in a comment. node --check and
  // check-modules cannot see an undefined reference; the grid failed to build on 2026-08-27
  // over exactly this (an import that never landed, and one that landed inside a header
  // comment), and smoke-ui was the first thing to notice.
  const code = src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
  if (f !== 'lexicon.js' && /\bt\('/.test(code) && !/import \{[^}]*\bt\b[^}]*\} from '\.\/lexicon\.js'/.test(code)) {
    fails.push(`${f} calls t() but does not import it from ./lexicon.js (in code — a comment does not count)`);
  }
  // A module that imports t and also names a local t: the scopes where `t` is not the word.
  if (/import \{[^}]*\bt\b[^}]*\} from '\.\/lexicon\.js'/.test(src)) {
    const locals = src.match(/\b(?:const|let|var)\s+t\b|\(\s*t\s*[,)]|\(\s*t\s*=>|\bt\s*=>|\b(?:const|let)\s+\[[^\]]*\bt\b[^\]]*\]\s*of/g) || [];
    if (locals.length) shadowers.push(`${f} (${locals.length})`);
  }
}
// index.html: the boot pass fills data-t / data-t-title / data-t-aria from the floor.
const html = fs.readFileSync(path.join(ROOT, 'public', 'index.html'), 'utf8');
for (const m of html.matchAll(/\bdata-t(?:-title|-aria)?="([\w.-]+)"/g)) read.add(m[1]);

// KOTOBA_GLOSSARY.md: the `glossary.*` room. No surface reads it; the boot shelf renders the
// glossary from it at session birth (src/session-boot.ts). Held three ways: every marked cell
// names a floor key whose word IS the cell's word; every glossary.* key in the floor is
// marked in the glossary (no orphans); a table row whose plain-English cell is a bold UI
// word carries a marker (a new row cannot be added unkeyed).
const glossary = fs.readFileSync(path.join(ROOT, 'KOTOBA_GLOSSARY.md'), 'utf8');
const marked = new Map();
for (const m of glossary.matchAll(/\*\*([^*\n]+)\*\*<!--g:([\w.-]+)-->/g)) {
  read.add(m[2]);
  if (!m[2].startsWith('glossary.')) fails.push(`KOTOBA_GLOSSARY.md marks \`${m[2]}\` — a glossary marker names a glossary.* key`);
  const prior = marked.get(m[2]);
  if (prior != null && prior !== m[1]) fails.push(`KOTOBA_GLOSSARY.md marks \`${m[2]}\` with two words: "${prior}" and "${m[1]}"`);
  marked.set(m[2], m[1]);
}
const floorWords = new Map();
for (const line of fs.readFileSync(path.join(LEX, `${FLOOR}.md`), 'utf8').split('\n')) {
  const m = /^-\s*\*\*([\w.-]+):\*\*\s*(.*?)\s*$/.exec(line.trim());
  if (m) floorWords.set(m[1], m[2]);
}
for (const [k, word] of marked) {
  if (!floorWords.has(k)) continue; // reported below as "the client reads … and the floor lacks it"
  if (floorWords.get(k) !== word) fails.push(`KOTOBA_GLOSSARY.md says "${word}" for \`${k}\` but ${FLOOR}.md says "${floorWords.get(k)}" — the floor IS the glossary's word; change both or neither`);
}
for (const k of floorWords.keys()) if (k.startsWith('glossary.') && !marked.has(k)) fails.push(`${FLOOR}.md carries \`${k}\` and KOTOBA_GLOSSARY.md marks no cell with it — an orphan glossary word`);
for (const line of glossary.split('\n')) {
  const m = /^\| (.+?) \| \*\*([^*]+)\*\*(?!<!--g:)/.exec(line);
  if (!m) continue;
  if (/^(⚠|—|\(no user word|see § OPEN)/.test(m[2]) || /^~~/.test(m[1]) || /^\*\*/.test(m[1])) continue;
  fails.push(`KOTOBA_GLOSSARY.md row "${m[1]}" names a UI word "${m[2]}" with no glossary.* marker — add \`<!--g:glossary.<term>-->\` and the floor line`);
}

for (const k of read) if (!PREFIXED.test(k) && !floor.has(k)) fails.push(`the client reads \`${k}\` and ${FLOOR}.md does not carry it`);
for (const f of lexicons) {
  const name = f.replace(/\.md$/, '');
  if (name === FLOOR) continue;
  for (const k of keysOf(path.join(LEX, f))) {
    if (!PREFIXED.test(k) && !floor.has(k)) fails.push(`${f} spells \`${k}\`, which ${FLOOR}.md does not carry — nothing to fall through to`);
  }
}
const unread = [...floor].filter((k) => !read.has(k) && !PREFIXED.test(k));

// ONE TABLE: docs/kokugo-table.md is generated from the catalog and must not be behind it.
try {
  execFileSync(process.execPath, [path.join(ROOT, 'scripts', 'kokugo-table.mjs'), '--check'], { stdio: 'pipe' });
} catch {
  fails.push('docs/kokugo-table.md is stale — run `node scripts/kokugo-table.mjs` and commit the page');
}

for (const line of fails) console.log(`  FAIL  ${line}`);
if (unread.length) console.log(`  note  ${unread.length} floor key(s) no view reads yet: ${unread.join(', ')}`);
if (shadowers.length) console.log(`  note  ${shadowers.length} module(s) import t and also name a local t — read those scopes: ${shadowers.join(', ')}`);
console.log(fails.length ? `check-lexicon: ${fails.length} failure(s)` : `check-lexicon: the floor holds (${floor.size} keys, ${read.size} read by the client, ${lexicons.length} lexicons)`);
process.exit(fails.length ? 1 : 0);
