#!/usr/bin/env node
/**
 * kokugo-table — ONE TABLE of every term the coworkspace reads, with every lexicon beside it.
 *
 *   npm run kokugo:table                     # write docs/kokugo-table.md
 *
 * ON DEMAND, NOT COMMITTED. The page is a REPORT built from the lexicons, and the lexicons
 * are the source. Committing it earned a merge conflict on every wording change — two
 * sessions touching one key collided on 1,700 lines of machine output — while asserting
 * nothing that check-lexicon's real findings do not already cover: the floor is complete,
 * no lexicon spells a key nobody reads, and the glossary room agrees with KOTOBA_GLOSSARY.
 * Those keep us in line. A generated file matching its own generator never did.
 *
 * `professional_en` is the floor — the table of every term. The owner wants to SEE the
 * translations beside it (2026-08-27): key by key, the floor's word and each other
 * lexicon's word, blank where that lexicon falls through. Generated, never hand-kept:
 *
 * Stock ⊕ yours: a lexicon file in the owner's catalogs store (`bin/ronin-store catalogs`
 * → `lexicons/<name>.md`) replaces the stock file of the same name whole, and a new name
 * is a new column — the same shadowing rule the server applies (docs/shadowing.md).
 *
 * Grouped by room: the part of the key before its first dot. A bare key (`campaign`) is
 * the room `(bare)`; a catalog token (`kind.household`) is the room `kind`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const STOCK = path.join(ROOT, 'ronin_catalogs', 'lexicons');
const OUT = path.join(ROOT, 'docs', 'kokugo-table.md');
const FLOOR = 'professional_en';
const FIELDS = new Set(['label', 'blurb', 'base', 'order', 'hidden']);

const parse = (file) => {
  const words = new Map();
  const fields = {};
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    const m = /^-\s*\*\*([\w.-]+):\*\*\s*(.*?)\s*$/.exec(line.trim());
    if (!m) continue;
    if (FIELDS.has(m[1])) fields[m[1]] = m[2];
    else words.set(m[1], m[2]);
  }
  return { words, fields };
};

/** Stock files, then the owner's store shadowing them whole by name. */
const files = new Map();
for (const f of fs.readdirSync(STOCK)) if (f.endsWith('.md') && f !== 'README.md') files.set(f.replace(/\.md$/, ''), path.join(STOCK, f));
let store = '';
try {
  store = execFileSync(path.join(ROOT, 'bin', 'ronin-store'), ['catalogs'], { encoding: 'utf8' }).trim();
} catch {
  store = '';
}
const yours = store ? path.join(store, 'lexicons') : '';
if (yours && fs.existsSync(yours)) {
  for (const f of fs.readdirSync(yours)) if (f.endsWith('.md') && f !== 'README.md') files.set(f.replace(/\.md$/, ''), path.join(yours, f));
}

const lexicons = new Map([...files].map(([name, file]) => [name, parse(file)]));
if (!lexicons.has(FLOOR)) {
  console.error(`kokugo-table: no ${FLOOR}.md — the floor is missing`);
  process.exit(2);
}
const others = [...lexicons.keys()].filter((n) => n !== FLOOR && !/^\s*yes\s*$/i.test(lexicons.get(n).fields.hidden || '')).sort();
const keys = new Set();
for (const { words } of lexicons.values()) for (const k of words.keys()) keys.add(k);

const roomOf = (k) => (k.includes('.') ? k.slice(0, k.indexOf('.')) : '(bare)');
const rooms = new Map();
for (const k of [...keys].sort()) {
  const r = roomOf(k);
  if (!rooms.has(r)) rooms.set(r, []);
  rooms.get(r).push(k);
}
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|');

const floor = lexicons.get(FLOOR);
const lines = [];
lines.push('# KOKUGO — the table of every term');
lines.push('');
lines.push('> **Generated by `npm run kokugo:table` — do not edit, and do not commit.** It is a report');
lines.push('> built from the lexicons, which are the source. Regenerate whenever you want to read it.');
lines.push('');
lines.push(`\`${FLOOR}\` is the floor: every key a surface reads, in plain English. Each other column is one`);
lines.push('lexicon (`ronin_catalogs/lexicons/`, shadowed whole-file by your catalogs store): its word where it');
lines.push('says one, blank where it falls through to the floor. A catalog token (`kind.*`, `role.*`,');
lines.push('`behaviour.*` may be blank in the floor too — the definition\'s own label is its floor.');
lines.push('Rooms are the part of a key before its first dot. `docs/kokugo.md` says how a view adds a word.');
lines.push('');
lines.push(`${keys.size} keys · ${rooms.size} rooms · lexicons: ${[FLOOR, ...others].map((n) => `\`${n}\` (${lexicons.get(n).fields.label || n})`).join(' · ')}`);
lines.push('');
const header = `| key | ${[FLOOR, ...others].join(' | ')} |`;
const rule = `|---|${[FLOOR, ...others].map(() => '---').join('|')}|`;
for (const [room, ks] of rooms) {
  lines.push(`## ${room}`);
  lines.push('');
  lines.push(header);
  lines.push(rule);
  for (const k of ks) {
    lines.push(`| \`${k}\` | ${cell(floor.words.get(k))} | ${others.map((n) => cell(lexicons.get(n).words.get(k))).join(' | ')} |`);
  }
  lines.push('');
}
const text = lines.join('\n');

fs.writeFileSync(OUT, text);
console.log(`kokugo-table: wrote docs/kokugo-table.md (${keys.size} keys, ${rooms.size} rooms, ${1 + others.length} lexicons)`);
